management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/recipes-manager"
      exposure:
        include: info
  endpoint:
    info:
      enabled: true
  server:
    port: 8444

server:
  port: 8443

spring:
  cloud:
    gcp:
      project-id: pasame-la-receta-java
