# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build project

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Calculate docker image name and tag
        run: |
          projectVersion=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
          buildVersion="$projectVersion-${{ github.event.pull_request.number }}"
          artifactId=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "buildVersion=$buildVersion" >> $GITHUB_ENV
          echo "artifactId=$artifactId" >> $GITHUB_ENV

      - name: Upgrade pom version
        run: mvn build-helper:parse-version versions:set -DnewVersion=$buildVersion

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        run: |
          docker build -t carlosjfcasero/${{ env.artifactId }}:${{ env.buildVersion }} -t carlosjfcasero/${{ env.artifactId }}:latest --platform linux/amd64,linux/arm64,linux/arm/v7 --push .